name: Auto-deploy production

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  fly-deploy:
    name: Fly deploy
    needs: fly-secrets
    uses: ./.github/workflows/fly-deploy.yml
    secrets: inherit
    with:
      changelog: ${{ github.event.release.body }}
      commitish: ${{ github.event.release.tag_name }}
      deeplink: ${{ github.event.release.html_url }}
      environment: production

  fly-secrets:
    name: Fly secrets
    uses: ./.github/workflows/fly-secrets.yml
    secrets: inherit
    with:
      environment: production
      stage_only: true
